### ISSUE TITLE
ДМ-2, Коллок, Вычислимость 19 билет, лажа с V'

### ISSUE THREAD

**Issue by SphericalPotatoInVacuum** [DKozl50/Matan2-tex#168]

**Comment by DKozl50** [comment]
А в чем именно тут беды?

**Comment by SphericalPotatoInVacuum** [comment]
Первый переход в строке с V' какой-то странный. Который про то что n \in k <=> dom V^\prime_n != 2N

**Comment by DKozl50** [comment]
Напомню, что V' = 1 если `n \in K` <ins>или</ins> `x` делится на два
Если `n \in K`, то подходит любой `x`, а это значит что `dom V'_n = N`. Так как `N \neq 2N` все получается верно.

**Comment by DKozl50** [comment]
Очень не хочу это писать в документе, потому что, кажется мне, вылезу за пределы страницы. Думаю читатели обнаружат этот скрытый переход

**Comment by SphericalPotatoInVacuum** [comment]
Ну на коллоке такое решение забанили назвав неправильным, так что не знаю короче.

**Comment by DKozl50** [comment]
Привет будущим второкурсникам тогда!

Тогда закрываю issue пока кто-то не расскажет где мы неправы
