### ISSUE TITLE
Ошибка в пункте 22

### ISSUE THREAD

**Issue by BoloniniD** [DKozl50/Matan2-tex#36]
Кажется там что-то не так с о-малыми.

**Comment by BoloniniD** [comment]
![photo_2020-06-03_02-53-13](https://user-images.githubusercontent.com/54375878/96155735-f3de5c80-0f18-11eb-9b67-133033daf0ea.png)

**Comment by maximkm** [comment]
Всё нормально, в скобках получается 1/n - 3/n^2 + o(1/n^2) = 1/n + o(1/n). Раскрываем скобки и получаем 1/n^3 + o(1/n^3). Ещё можно посмотреть конец 2 лекции, там это разбиралось.

P.S. коллоквиум завершается с оценкой 0 :weirdmaiewski:

**Comment by shoraii** [comment]
>Ever get that feeling of déjà vu?
